### PR TITLE
Add solution

### PR DESCRIPTION
**Pull request by WaveOfDandelions**
GH: https://waveofdandelions.github.io/react_person/

### CODE REVIEW

**Comment by cardinal1991** [comment]
Code looks great to me,  you may put demo page link in the description.

**Review by cardinal1991 — APPROVED** [review]
Looks good to me.

**Review by cardinal1991 — APPROVED** [review]

**Review by choeqq — APPROVED** [review]
Please provide demo link in description

**Comment by WaveOfDandelions** [comment]
> Please provide demo link in description

GH: https://WaveOfDandelions.github.io/react_person/

**Pull request closed without merging**
