### PR TITLE
Solution

### PR DESCRIPTION
**Pull request by SashaViun**
[DEMO LINK](https://SashaViun.github.io/react_decompose/)

### CODE REVIEW

**Comment by ihor-soloviov** [comment]
Good job! I really don't understand what kind of problem was founded in tests. I'd like to see mentor's review

**Comment by alexandra-protyanova** [comment]
Снимок экрана 2023-01-26 в 11 29 59
Here is an error, which crashed tests

**Review by alexandra-protyanova — APPROVED** [review]
Move styles from `App.scss` to appropriate components.
Try to replace `export` with export default`

**Review by alexandra-protyanova — CHANGES_REQUESTED** [review]
Sorry, missclicked

**Pull request closed without merging**
