### PR TITLE
completed task

### PR DESCRIPTION
**Pull request by andrudenko**
[DEMO LINK](https://andrudenko.github.io/react_decompose/)

### CODE REVIEW

**Review by SerhiiKirik — CHANGES_REQUESTED** [review]
Great 🔥 
Let's deploy your solution
image

**Comment by andrudenko** [comment]
> Great 🔥 Let's deploy your solution image

unfortunately faced with issue
Screenshot 2023-04-04 at 00 17 39

it may be connected that on first attempt I coppied from mate_academy repo changes and after that made fork to my repository and made all necessary changes there, but at the moment can't fix the issue. Could you please assist?

**Review by SerhiiKirik — CHANGES_REQUESTED** [review]
Let's try to fix this problem in slack chat 🧑‍💻

**Comment by andrudenko** [comment]
> Let's try to fix this problem in slack chat 🧑‍💻

I tried to repeat everything from scratch. Closed current PR, removed all files locally and cloned the data again. Issue is gone after rework. Please check new PR for the task https://github.com/mate-academy/react_decompose/pull/1724

**Pull request closed without merging**
